/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_v1_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        /** Delete Workspace */
        delete: operations["delete_workspace_api_v1_workspaces__workspace_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/editor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Editor */
        put: operations["save_editor_api_v1_workspaces__workspace_id__editor_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_workspaces__workspace_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/task-sets/{task_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Task Set */
        delete: operations["delete_task_set_api_v1_workspaces__workspace_id__task_sets__task_set_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_workspaces__workspace_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_v1_workspaces__workspace_id__runs__run_id__get"];
        put?: never;
        post?: never;
        /** Cancel */
        delete: operations["cancel_api_v1_workspaces__workspace_id__runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outcomes */
        get: operations["outcomes_api_v1_workspaces__workspace_id__runs__run_id__outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_workspaces__workspace_id__runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comparison */
        post: operations["comparison_api_v1_workspaces__workspace_id__runs__run_id__comparison_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/results/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_api_v1_workspaces__workspace_id__runs__run_id__results__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/exports/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_v1_workspaces__workspace_id__runs__run_id__exports__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfig */
        AppConfig: {
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Ready */
            ready: boolean;
            error: components["schemas"]["ErrorEnvelope"] | null;
            /**
             * Generator Version
             * @default 1
             */
            generator_version: string;
            /**
             * Engine Version
             * @default value-stream-app-1
             */
            engine_version: string;
        };
        /** Backlog */
        Backlog: {
            /** Stage */
            stage: string;
            /** Label */
            label: string;
            /** Time */
            time: number[];
            /** Waiting */
            waiting: number[];
            /**
             * Reduced
             * @default false
             */
            reduced: boolean;
        };
        /** ComparisonMutation */
        ComparisonMutation: {
            /**
             * Action
             * @enum {string}
             */
            action: "pin" | "unpin" | "baseline" | "delete";
        };
        /** ConcreteScenario */
        ConcreteScenario: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Definition Id
             * Format: uuid
             */
            definition_id: string;
            /** Revision */
            revision: number;
            /** Name */
            name: string;
            settings: components["schemas"]["ModelSettings-Output"];
            /** Team Seed */
            team_seed: number;
            /** Execution Seed */
            execution_seed: number;
            model: components["schemas"]["ModelInput"];
        };
        /** ConstantValue */
        "ConstantValue-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "constant";
            /**
             * Value
             * @default 1
             */
            value: number;
        };
        /** ConstantValue */
        "ConstantValue-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "constant";
            /**
             * Value
             * @default 1
             */
            value: number;
        };
        /** DeveloperInput */
        DeveloperInput: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Efficiency
             * @default 1
             */
            efficiency: number;
        };
        /** EditorRequest */
        EditorRequest: {
            /** Expected Revision */
            expected_revision: number;
            task_spec: components["schemas"]["TaskSetSpec-Input"];
            /** Definitions */
            definitions: components["schemas"]["ScenarioDefinition-Input"][];
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ModelInput */
        ModelInput: {
            /** Developer Team */
            developer_team: components["schemas"]["DeveloperInput"][];
            /** Deployment Cadence */
            deployment_cadence: number;
            /** Qa Testers */
            qa_testers: components["schemas"]["QAPoolInput"] | components["schemas"]["QAListInput"];
            /** Toolchain Pool */
            toolchain_pool: components["schemas"]["ToolchainPoolInput"] | components["schemas"]["ToolchainListInput"];
            /** Support Interval */
            support_interval?: number | null;
            /**
             * Support Task Story Points
             * @default 1
             */
            support_task_story_points: number;
        };
        /** ModelSettings */
        "ModelSettings-Input": {
            /**
             * Team Size
             * @default 4
             */
            team_size: number;
            /**
             * Efficiency Min
             * @default 0.5
             */
            efficiency_min: number;
            /**
             * Efficiency Max
             * @default 1.5
             */
            efficiency_max: number;
            /**
             * Distribution
             * @default linear
             * @enum {string}
             */
            distribution: "linear" | "normal";
            /**
             * Deployment Cadence
             * @default 5
             */
            deployment_cadence: number;
            /**
             * Qa Size
             * @default 5
             */
            qa_size: number;
            /**
             * Qa Time Cost
             * @default 0.1
             */
            qa_time_cost: number;
            /**
             * Qa Failure Rate
             * @default 0.15
             */
            qa_failure_rate: number;
            /**
             * Qa Failure Cost
             * @default 0.25
             */
            qa_failure_cost: number;
            /**
             * Toolchain Size
             * @default 20
             */
            toolchain_size: number;
            /**
             * Deployment Duration
             * @default 0.25
             */
            deployment_duration: number;
            /**
             * Deployment Failure Rate
             * @default 0.1
             */
            deployment_failure_rate: number;
            /**
             * Support Interval
             * @default 5
             */
            support_interval: number | null;
            /**
             * Support Task Story Points
             * @default 2
             */
            support_task_story_points: number;
        };
        /** ModelSettings */
        "ModelSettings-Output": {
            /**
             * Team Size
             * @default 4
             */
            team_size: number;
            /**
             * Efficiency Min
             * @default 0.5
             */
            efficiency_min: number;
            /**
             * Efficiency Max
             * @default 1.5
             */
            efficiency_max: number;
            /**
             * Distribution
             * @default linear
             * @enum {string}
             */
            distribution: "linear" | "normal";
            /**
             * Deployment Cadence
             * @default 5
             */
            deployment_cadence: number;
            /**
             * Qa Size
             * @default 5
             */
            qa_size: number;
            /**
             * Qa Time Cost
             * @default 0.1
             */
            qa_time_cost: number;
            /**
             * Qa Failure Rate
             * @default 0.15
             */
            qa_failure_rate: number;
            /**
             * Qa Failure Cost
             * @default 0.25
             */
            qa_failure_cost: number;
            /**
             * Toolchain Size
             * @default 20
             */
            toolchain_size: number;
            /**
             * Deployment Duration
             * @default 0.25
             */
            deployment_duration: number;
            /**
             * Deployment Failure Rate
             * @default 0.1
             */
            deployment_failure_rate: number;
            /**
             * Support Interval
             * @default 5
             */
            support_interval: number | null;
            /**
             * Support Task Story Points
             * @default 2
             */
            support_task_story_points: number;
        };
        /** Observation */
        Observation: {
            /** Rule */
            rule: string;
            /** Message */
            message: string;
            /** Evidence */
            evidence: string;
            /** Property */
            property: string | null;
            /** Value */
            value: number | string | null;
        };
        /** OutcomeSummary */
        OutcomeSummary: {
            scenario: components["schemas"]["ConcreteScenario"];
            /** @default queued */
            status: components["schemas"]["Status"];
            /**
             * Cursor
             * @default 0
             */
            cursor: number;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Loss Percent */
            loss_percent: number | null;
            /** Completion Time */
            completion_time: number | null;
            /** Delivered Value */
            delivered_value: number | null;
            error: components["schemas"]["ErrorEnvelope"] | null;
        };
        /** PlotData */
        PlotData: {
            /** Loss Percent */
            loss_percent: number | null;
            /** Stages */
            stages: components["schemas"]["StageLoss"][];
            /** Activity */
            activity: components["schemas"]["ResourceActivity"][];
            /** Backlog */
            backlog: components["schemas"]["Backlog"][];
        };
        /** Preview */
        Preview: {
            /** Digest */
            digest: string;
            /**
             * Task Set Id
             * Format: uuid
             */
            task_set_id: string;
            /** Workspace Revision */
            workspace_revision: number;
            /** Scenarios */
            scenarios: components["schemas"]["ConcreteScenario"][];
            /** Count */
            count: number;
        };
        /** QAInput */
        QAInput: {
            /**
             * Time Cost
             * @default 0.1
             */
            time_cost: number;
            /**
             * Failure Rate
             * @default 0
             */
            failure_rate: number;
            /**
             * Failure Cost
             * @default 0
             */
            failure_cost: number;
        };
        /** QAListInput */
        QAListInput: {
            /**
             * Kind
             * @default list
             * @constant
             */
            kind: "list";
            /** Resources */
            resources: components["schemas"]["QAInput"][];
        };
        /** QAPoolInput */
        QAPoolInput: {
            /**
             * Time Cost
             * @default 0.1
             */
            time_cost: number;
            /**
             * Failure Rate
             * @default 0
             */
            failure_rate: number;
            /**
             * Failure Cost
             * @default 0
             */
            failure_cost: number;
            /**
             * Kind
             * @default pool
             * @constant
             */
            kind: "pool";
            /** Limit */
            limit: number;
        };
        /** ResourceActivity */
        ResourceActivity: {
            /** Stage */
            stage: string;
            /** Label */
            label: string;
            /** Durations */
            durations: {
                [key: string]: number;
            };
            /** Shares */
            shares: {
                [key: string]: number | null;
            };
        };
        /** ResultView */
        ResultView: {
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            metrics: components["schemas"]["PlotData"];
            /** Observations */
            observations: components["schemas"]["Observation"][];
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Preview Digest */
            preview_digest: string;
            /**
             * Name
             * @default Baseline
             */
            name: string;
            /**
             * Intent
             * @default manual
             * @enum {string}
             */
            intent: "manual" | "interactive";
            /** Source Run Id */
            source_run_id?: string | null;
            /** Property */
            property?: string | null;
            /** Value */
            value?: number | string | null;
            /** Definition Id */
            definition_id?: string | null;
            /** Family Value */
            family_value?: number | string | null;
        };
        /** RunStatus */
        RunStatus: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Task Set Id
             * Format: uuid
             */
            task_set_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "submitting" | "queued" | "running" | "reconnecting" | "cancelling" | "completed" | "completed_with_errors" | "cancelled" | "failed";
            /** Intent */
            intent: string;
            /** Job Id */
            job_id: string | null;
            /** Outcomes */
            outcomes: components["schemas"]["OutcomeSummary"][];
            /**
             * Last Cursor
             * @default 0
             */
            last_cursor: number;
            error: components["schemas"]["ErrorEnvelope"] | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /**
             * Superseded
             * @default false
             */
            superseded: boolean;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /**
             * Retry Paused
             * @default false
             */
            retry_paused: boolean;
        };
        /** ScenarioDefinition */
        "ScenarioDefinition-Input": {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Name
             * @default Delivery model
             */
            name: string;
            /**
             * Revision
             * @default 1
             */
            revision: number;
            settings?: components["schemas"]["ModelSettings-Input"];
            /** Sweeps */
            sweeps?: {
                [key: string]: (number | string | null)[] | components["schemas"]["SweepRange"];
            };
            /**
             * Team Seed
             * @default 123
             */
            team_seed: number;
            /**
             * Execution Seed
             * @default 456
             */
            execution_seed: number;
        };
        /** ScenarioDefinition */
        "ScenarioDefinition-Output": {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name
             * @default Delivery model
             */
            name: string;
            /**
             * Revision
             * @default 1
             */
            revision: number;
            settings: components["schemas"]["ModelSettings-Output"];
            /** Sweeps */
            sweeps: {
                [key: string]: (number | string | null)[] | components["schemas"]["SweepRange"];
            };
            /**
             * Team Seed
             * @default 123
             */
            team_seed: number;
            /**
             * Execution Seed
             * @default 456
             */
            execution_seed: number;
        };
        /** StageLoss */
        StageLoss: {
            /** Stage */
            stage: string;
            /** Label */
            label: string;
            /** Loss Percent */
            loss_percent: number;
            /** Visits */
            visits: number;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** SweepRange */
        SweepRange: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Step */
            step: number;
        };
        /** TaskInput */
        TaskInput: {
            /** Initial Value */
            initial_value: number;
            /** Story Points */
            story_points: number;
            /**
             * Depreciation Rate
             * @default 0.005
             */
            depreciation_rate: number;
            /** Task Name */
            task_name?: string | null;
            /**
             * Creation Sim T
             * @default 0
             */
            creation_sim_t: number;
            /**
             * Task Type
             * @default development
             * @enum {string}
             */
            task_type: "development" | "support";
            /**
             * Is Rework
             * @default false
             */
            is_rework: boolean;
        };
        /** TaskSet */
        TaskSet: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Revision
             * @default 1
             */
            revision: number;
            spec: components["schemas"]["TaskSetSpec-Output"];
            /** Content Hash */
            content_hash: string;
            /** Tasks */
            tasks: components["schemas"]["TaskInput"][];
            /**
             * Generator Version
             * @default 1
             */
            generator_version: string;
        };
        /** TaskSetSpec */
        "TaskSetSpec-Input": {
            /**
             * Name
             * @default Task set
             */
            name: string;
            /**
             * Count
             * @default 500
             */
            count: number;
            /** Story Points */
            story_points?: components["schemas"]["ConstantValue-Input"] | components["schemas"]["UniformValue-Input"];
            /** Initial Value */
            initial_value?: components["schemas"]["ConstantValue-Input"] | components["schemas"]["UniformValue-Input"];
            /**
             * Depreciation Rate
             * @default 0.02
             */
            depreciation_rate: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** TaskSetSpec */
        "TaskSetSpec-Output": {
            /**
             * Name
             * @default Task set
             */
            name: string;
            /**
             * Count
             * @default 500
             */
            count: number;
            /** Story Points */
            story_points: components["schemas"]["ConstantValue-Output"] | components["schemas"]["UniformValue-Output"];
            /** Initial Value */
            initial_value: components["schemas"]["ConstantValue-Output"] | components["schemas"]["UniformValue-Output"];
            /**
             * Depreciation Rate
             * @default 0.02
             */
            depreciation_rate: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** ToolchainInput */
        ToolchainInput: {
            /** Deployment Duration */
            deployment_duration: number;
            /**
             * Failure Rate
             * @default 0
             */
            failure_rate: number;
        };
        /** ToolchainListInput */
        ToolchainListInput: {
            /**
             * Kind
             * @default list
             * @constant
             */
            kind: "list";
            /** Resources */
            resources: components["schemas"]["ToolchainInput"][];
        };
        /** ToolchainPoolInput */
        ToolchainPoolInput: {
            /** Deployment Duration */
            deployment_duration: number;
            /**
             * Failure Rate
             * @default 0
             */
            failure_rate: number;
            /**
             * Kind
             * @default pool
             * @constant
             */
            kind: "pool";
            /** Limit */
            limit: number;
        };
        /** UniformValue */
        "UniformValue-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "uniform";
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
        };
        /** UniformValue */
        "UniformValue-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "uniform";
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
        };
        /** Workspace */
        Workspace: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            task_spec: components["schemas"]["TaskSetSpec-Output"];
            /** Definitions */
            definitions: components["schemas"]["ScenarioDefinition-Output"][];
            /** Task Sets */
            task_sets: components["schemas"]["TaskSet"][];
            /** Current Task Set */
            current_task_set: string | null;
            /** Baseline Id */
            baseline_id: string | null;
            /** Latest Id */
            latest_id: string | null;
            /** Runs */
            runs: components["schemas"]["RunStatus"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    create_workspace_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    workspace_api_v1_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_workspace_api_v1_workspaces__workspace_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    save_editor_api_v1_workspaces__workspace_id__editor_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    preview_api_v1_workspaces__workspace_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_task_set_api_v1_workspaces__workspace_id__task_sets__task_set_id__delete: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: never;
            path: {
                workspace_id: string;
                task_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    start_run_api_v1_workspaces__workspace_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    run_api_v1_workspaces__workspace_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancel_api_v1_workspaces__workspace_id__runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    outcomes_api_v1_workspaces__workspace_id__runs__run_id__outcomes_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeSummary"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resume_api_v1_workspaces__workspace_id__runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    comparison_api_v1_workspaces__workspace_id__runs__run_id__comparison_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    result_api_v1_workspaces__workspace_id__runs__run_id__results__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    export_api_v1_workspaces__workspace_id__runs__run_id__exports__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                run_id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
