name: CI

on:
  push:
    branches: [ main, feature/* ]
    tags-ignore: [ 'v*']

  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  validate:
    uses: ./.github/workflows/validate.yml
    needs:
      - test
