name: Release

on:
    push:
      tags: 
        - 'v*'

jobs:

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate package version consistency
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PACKAGE_VERSION=$(python -c "import value_stream.__version__ as v; print(v.__version__)")

          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Version mismatch! GitHub tag is $TAG_VERSION but package version is $PACKAGE_VERSION."
            exit 1
          fi

  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  validate:
      uses: ./.github/workflows/validate.yml
      needs:
        - test

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs: 
      - validate
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/value-stream
    permissions:
      id-token: write
    
    steps:
    - name: Download distribution
      uses: actions/download-artifact@v6
      with:
        name: python-artifacts
        path: dist/app
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/app/
